[server]
port = 8080

[github]
token = ""

[persistence]
sqlite_path = "releases.db"

[refresh]
interval_secs = 300

[sls.modules]
accumulations = "Накопления"
bonuses = "Бонусы"
communications = "Коммуникации"
coupons = "Купоны"
customers = "Покупатели"
discounts = "Скидки"
dwh = "Аналитика"
favorites = "Любимый товар"
gateway = "gateway"
limits = "Лимиты"
offers = "Офферы"
purchases = "Чеки"
registrations = "Регистрации"
segments = "Сегменты"
triggers = "Триггеры"
scheduler = "Планировщик"
superset = "Superset"
superset-integration = "Superset Интеграция"
frontend-loyalty = "Фронтенд Лояльности"
frontend-registrations = "Фронтенд Регистрации"
