ktor:
    application:
        modules:
            - ru.crystals.sls.releases.ApplicationKt.module
    deployment:
        port: 8080

github:
    token: $GITHUB_TOKEN

sls:
    modules:
        accumulations: "Накопления"
        bonuses: "Бонусы"
        communications: "Коммуникации"
        coupons: "Купоны"
        customers: "Покупатели"
        discounts: "Скидки"
        dwh: "Аналитика"
        gateway: "gateway"
        limits: "Лимиты"
        offers: "Офферы"
        purchases: "Чеки"
        registrations: "Регистрации"
        segments: "Сегменты"
        triggers: "Триггеры"
        scheduler: "scheduler"
        superset: "superset"
        superset-integration: "superset-integration"
